name: nf-core-mirnatargetdetector-1.0dev
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.7
  - miranda
  - pyfasta
  - numpy
  - bioconda::meme
  - genomedk::rnahybrid
  - bioconda::pyfastaq
